{
  "simplesamlphp_secrets": {
    "secretsalt": "y0h9d13pki9qdhfm3l5nws4jjn55j6hj",
    "auth.adminpassword": {
      "@local": "localsecret",
      "@dev": "devsecret",
      "@test": "testsecret",
      "@prod": "prodsecret"
    }
  }
}
